language: node_js

node_js:
  - "0.10"

script:
  make test-cov

after_success:
  - cat ./coverage/lcov.info | ./node_modules/codeclimate-test-reporter/bin/codeclimate.js
  - cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js

addons:
  code_climate:
    repo_token: 881a65b7e0d735981080166d5d671a041077e0179e3953048c3f71c793dec5ac

